"""initial schema

Revision ID: 2231fc28883f
Revises: 
Create Date: 2026-08-16 20:20:54.179535

"""
from collections.abc import Sequence

import pgvector
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '2231fc28883f'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('ats_provider', sa.Text(), nullable=True),
    sa.Column('board_token', sa.Text(), nullable=True),
    sa.Column('country', sa.Text(), nullable=True),
    sa.Column('discovered_via', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tier', sa.Text(), nullable=True),
    sa.Column('quota_remaining', sa.Integer(), nullable=True),
    sa.Column('quota_reset_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jobs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('url_hash', sa.Text(), nullable=False),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('ats_provider', sa.Text(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('work_arrangement', sa.Text(), nullable=True),
    sa.Column('department', sa.Text(), nullable=True),
    sa.Column('comp_min', sa.Integer(), nullable=True),
    sa.Column('comp_max', sa.Integer(), nullable=True),
    sa.Column('raw_jd', sa.Text(), nullable=True),
    sa.Column('extracted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('seniority', sa.Text(), nullable=True),
    sa.Column('hard_requirements', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('nice_to_haves', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('skill_ids', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('synthesized_doc', sa.Text(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url_hash', name='uq_jobs_url_hash')
    )
    op.create_table('user_filters',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title_families', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('locations', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('comp_floor', sa.Integer(), nullable=True),
    sa.Column('seniority_band', sa.Text(), nullable=True),
    sa.Column('work_arrangement', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('user_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column(
        'work_history',
        postgresql.JSONB(astext_type=sa.Text()),
        server_default='[]',
        nullable=False,
    ),
    sa.Column('skill_ids', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('synthesized_doc', sa.Text(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.Column('profile_version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('rematch_needed', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('matches',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('cycle_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('rerank_score', sa.Float(), nullable=True),
    sa.Column('gate_verdict', sa.Text(), nullable=True),
    sa.Column('gate_reason', sa.Text(), nullable=True),
    sa.Column('matched_skills', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('adjacent_skills', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('missing_skills', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pipeline_events',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('job_id', sa.UUID(), nullable=True),
    sa.Column('stage', sa.String(length=64), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('generations',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('match_id', sa.UUID(), nullable=False),
    sa.Column('resume_doc', sa.Text(), nullable=True),
    sa.Column('claim_source_map', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('verify_status', sa.Text(), nullable=True),
    sa.Column('verify_failures', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('generations')
    op.drop_table('pipeline_events')
    op.drop_table('matches')
    op.drop_table('user_profiles')
    op.drop_table('user_filters')
    op.drop_table('jobs')
    op.drop_table('users')
    op.drop_table('companies')
    # ### end Alembic commands ###
    op.execute("DROP EXTENSION IF EXISTS vector")
